name: alang-ml-parser
version: '0.1.0'
category: Devel
author: Justus Adam
maintainer: dev@justus.science
copyright: © 2018 Justus Adam
license: OtherLicense
github: ohua-dev/alang-ml-parser
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- ohua-core
- bytestring
default-extensions:
- NoImplicitPrelude
library:
  source-dirs: src
  exposed-modules:
  - Ohua.Compat.ML.Lexer
  - Ohua.Compat.ML.Parser
  dependencies:
  - array
  - unordered-containers
  build-tools:
  - alex
  - happy
tests:
  alang-sexpr-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alang-ml-parser
    - hspec
