resolver: lts-12.10
packages:
- .
- location:
    git: https://github.com/ohua-dev/ohua-core
    commit: 40487923258fa753ad5bc23c883abedbe2cbe828
  subdirs: [core, test-tools]
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
